export default {
	HankenGrotesk_100Thin: "HankenGrotesk_100Thin",
	HankenGrotesk_200ExtraLight: "HankenGrotesk_200ExtraLight",
	HankenGrotesk_300Light: "HankenGrotesk_300Light",
	HankenGrotesk_400Regular: "HankenGrotesk_400Regular",
	HankenGrotesk_500Medium: "HankenGrotesk_500Medium",
	HankenGrotesk_600SemiBold: "HankenGrotesk_600SemiBold",
	HankenGrotesk_700Bold: "HankenGrotesk_700Bold",
	HankenGrotesk_800ExtraBold: "HankenGrotesk_800ExtraBold",
	HankenGrotesk_900Black: "HankenGrotesk_900Black",
	HankenGrotesk_100Thin_Italic: "HankenGrotesk_100Thin_Italic",
	HankenGrotesk_200ExtraLight_Italic: "HankenGrotesk_200ExtraLight_Italic",
	HankenGrotesk_300Light_Italic: "HankenGrotesk_300Light_Italic",
	HankenGrotesk_400Regular_Italic: "HankenGrotesk_400Regular_Italic",
	HankenGrotesk_500Medium_Italic: "HankenGrotesk_500Medium_Italic",
	HankenGrotesk_600SemiBold_Italic: "HankenGrotesk_600SemiBold_Italic",
	HankenGrotesk_700Bold_Italic: "HankenGrotesk_700Bold_Italic",
	HankenGrotesk_800ExtraBold_Italic: "HankenGrotesk_800ExtraBold_Italic",
	HankenGrotesk_900Black_Italic: "HankenGrotesk_900Black_Italic",
};
